name: Đúc APK Tự Động

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04 # Hạ xuống bản hệ điều hành siêu ổn định

    steps:
      - name: Lấy Code về Lò
        uses: actions/checkout@v4

      - name: Cài đặt Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Hạ Python xuống cho chuẩn bài

      - name: Cài đặt Java (Búa máy)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Chữa bệnh thiếu linh kiện Linux
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev

      - name: Nạp FLET BẢN VÀNG (0.23.2)
        run: |
          python -m pip install --upgrade pip
          pip install flet==0.23.2
          pip install -r requirements.txt

      - name: ÉP KHUÔN APK (Tuyệt kỹ luồn lách)
        run: |
          set +e
          yes | flet build apk
          FLET_EXIT=${PIPESTATUS[1]}
          exit $FLET_EXIT

      - name: Trả Hàng (Lưu file APK)
        uses: actions/upload-artifact@v4
        with:
          name: App_Kienentti_APK
          path: build/apk/**/*.apk
